<!-- TOC -->

- [错误处理](#错误处理)
    - [异常错误的种类](#异常错误的种类)
        - [语法错误](#语法错误)
        - [数据类型错误](#数据类型错误)
        - [评估错误](#评估错误)
        - [范围错误](#范围错误)
        - [引用错误](#引用错误)
        - [网址在编码或解码上的错误](#网址在编码或解码上的错误)
        - [逻辑错误](#逻辑错误)
    - [处理特定异常错误](#处理特定异常错误)
        - [实验与捕获特定异常错误](#实验与捕获特定异常错误)
        - [抛出自定义的异常错误](#抛出自定义的异常错误)
    - [调试机制](#调试机制)
        - [严格模式](#严格模式)
        - [源代码的断点设置和逐句执行](#源代码的断点设置和逐句执行)

<!-- /TOC -->

# 错误处理

在支持特定编程语言的集成开发环境中，执行开发中的应用程序时，若发生任何异常错误，则汇编器、编译器或解释器，应该显示特定的错误信息，以便编程人员进行调试。

## 异常错误的种类

在JS中，常见的异常错误种类，大致如下：

1. 语法错误：syntax
2. 数据类型错误：data type
3. 范围错误：range
4. 引用错误：reference
5. 网址（URI/URL）的编码或者解码错误
6. 逻辑错误：logical

逻辑错误的主要原因是编程人员思考的不够周全而导致的，所以汇编器、编译器和解释器均难以察觉。


### 语法错误

JS引擎无法顺利解释特定语法时，便会产生语法错误。

```javascript
let v01 = 100, v02 = 230, result = 0;
try {
    eval('result = v01 -- v02;');
} catch(err) {
    console.log(err);  // SyntaxError: Unexpected identifier...
    console.log(typeof err);  // object
    console.log(err instanceof SyntaxError);  // true
    console.log(err.name);  // SyntaxError
    console.log(err.message);  // Unexpected identifier
    console.log(err.stack);  // SyntaxError: Unexpected identifier
}
```


### 数据类型错误

JS引擎无法顺利转换特定操作数的数据类型时，便会产生数据类型的错误。

```javascript
let v01 = 100, v02 = 230, result = 0;
try {
    result = v01.replace('0', '1');
    console.log(result);
} catch(err) {
    console.log(err);  // TypeError: v01.replace is not a function...
    console.log(typeof err);  // object
    console.log(err instanceof TypeError);  // true
    console.log(err.name);  // TypeError
    console.log(err.message);  // v01.replace is not a function
    console.log(err.stack);  // TypeError: v01.replace is not a function
}
```


### 评估错误

JS引擎现今只能通过内置函数【eval(代表特定语句的字符串)】或者语句【throw new EvalError(代表特定错误信息的字符串);】，才会产生评估错误。

```javascript
try {
    throw new EvalError('Equation evaluation error occurs!')
} catch(err) {
    console.log(err);  // EvalError: Equation evaluation error occurs!
    console.log(typeof err);  // object
    console.log(err instanceof EvalError);  // true
    console.log(err.name);  // EvalError
    console.log(err.message);  // Equation evaluation error occurs!
    console.log(err.stack);  // EvalError: Equation evaluation error occurs!
}
```


### 范围错误

JS引擎评估到特定数据范围以外的数据时，便会产生数据范围。

```javascript
let value = 200, list = null, result = 0;
try {
    list = new Array(-3);
    console.log(list);
} catch(err) {
    console.log(err);  // RangeError: Invalid array length
    console.log(typeof err);  // object
    console.log(err instanceof RangeError);  // true
    console.log(err.name);  // RangeError
    console.log(err.message);  // Invalid array length
    console.log(err.stack);  // RangeError: Invalid array length
}
```

### 引用错误

尚未被声明的变量名称，被引用时，会产生引用错误。

```javascript
let v01 = 100, v02 = 150, result = 0;
try {
    result = v01 + v03;
    console.log(result);
} catch(err) {
    console.log(err);  // ReferenceError: v03 is not defined
    console.log(typeof err);  // object
    console.log(err instanceof ReferenceError);  // true
    console.log(err.name);  // ReferenceError
    console.log(err.message);  // v03 is not defined
    console.log(err.stack);  // ReferenceError: v03 is not defined
}
```


### 网址在编码或解码上的错误

JS引擎无法顺利对特定网址进行编码或解码时，便会产生URI错误，引申为网址在编码或解码上的错误。

```javascript
try {
    decodeURIComponent('http://tw.dictionary.yahoo.com/dictionary?p=%E8%81%96%E8%AA%95%E7%AF%FF');
} catch(err) {
    console.log(err);  // URIError: URI malformed
    console.log(typeof err);  // object
    console.log(err instanceof URIError);  // true
    console.log(err.name);  // URIError
    console.log(err.message);  // URI malformed
    console.log(err.stack);  // URIError: URI malformed
}
```


### 逻辑错误

JS引擎无法察觉，编程人员思考的不够周全而导致的逻辑错误。

```javascript
let num_list = Array.from(new Array(11), (value, index) => {
    parseInt(100 * Math.random());
})
let result = null;
result = Math.min(...num_list);
console.log(num_list);
/* [ undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined ]
*/
console.log(result);  // NaN
console.log(`The maximum value is ${result}`);  // The maximum value is NaN

let radius = 55;
result = (3 / 4 * Math.PI * radius ** 3).toFixed(3);
console.log(`The sphere volume of radius ${radius} is ${result}`);  // The sphere volume of radius 55 is 392011.858
```


## 处理特定异常错误

在特定应用程序中，难免会潜藏着未被发觉的错误，进而导致用户在操作时，看见无法理解的相关错误信息。

欲转换原本无法 被理解的相关错误信息，成为用户可以理解或不会看见的错误信息，编程人员必须在其源代码中，拽写错误处理的相关部分。

```javascript
try {
    throw 'Logical error occurs.';
} catch(err) {
    console.log(err.name);  // undefined
    console.log(err.message);  // undefined
    console.log(err.stack);  // undefined
    console.log(`Special: ${err}`);  // Special: Logical error occurs.
} finally {
    console.log('Message after exception handing.');  // Message after exception handing.
}
```

### 实验与捕获特定异常错误

在JS语言中，可通过`try {...} catch {...} finally {...}`的语法达成实验（try）与捕获（catch）特定异常错误，最后（finally）综合处理的机制

### 抛出自定义的异常错误

通过关键字`throw`开头的语句，可使得JS引擎抛出特定自定义异常错误的对象实例。
`throw 'Logical error occurs.';`


## 调试机制

JS引擎支持如下两种调试机制：

1. 通过带有字符串字面量`use strict;`，启动JS引擎的严格模式；
2. 通过语句`debugger;`，在特定源代码的位置上，设置调试用途的断点。

### 严格模式

JS引擎处于严格模式的情况下，对于源代码的语法的要求，是相当严格的。

### 源代码的断点设置和逐句执行

在JS源代码中，可安排多个调试用途的断电的语句`debugger;`，以便JS引擎执行到特定断点时，可暂停并等待编程人员进一步的调试动作，比如逐句执行、调至下一个断点。

```javascript
let radius = 10, height = 15, result = 0;
result = Math.PI * (radius ** 2) * height;
console.log(result);  // 4712.38898038469

debugger;

result = 2 * Math.PI * radius ** 2 + 2 * Math.PI * radius * height;
console.log(result);  // 1570.7963267948967

debugger;

result = 4 / 3 * Math.PI * radius ** 3;
console.log(result);  // 4188.790204786391

debugger;

result = 4 * Math.PI * radius ** 2;
console.log(result);  // 1256.6370614359173
```
